module.exports.terms = `"005bd035-abe9-480d-a217-b1ef3f98dbca","Seekweb","Usually refers to SEEK’s main database, sometimes refers to the online component of SEEK’s business",
"00e44b6a-1cf6-4225-8794-3e0816bbf2a0","RATE CARD","Rate cards contain the pricing for all SEEK products and are usually updated in July. See Rate Cards Jive page",
"0c7e5692-5d20-41ae-8ec6-3b131a5610f9","Session","(Nielsen/NetRatings site metrics term.) A session occurs when a visitor comes to and navigates around your web site. A session may consist of single or multiple page views. The visit persists until 30 minutes of inactivity or 12 hours of continuous activity.",
"10e494c3-5c56-4ab5-851c-f47b2d41262f","Bulk Imports","Also known as BI, Fastlane, or Fastlane Plus; a method used for uploading multiple ads without using CAJA. See  Fastlane Plus Project (Bulk Imports) for more information.",
"122235f4-2dbc-4861-8c5f-9c9fad2374d4","SERP","Search engine results page ","Search engine results page"
"1243fcca-8d3f-4be7-ac6a-b77e74a63ffb","Mirror A Job Ad (Maja)","There are others but most of the functionality relating to the others is now legacy e.g. Adecco",
"12c6b7b7-6b96-49ca-b028-b1f612c1600b","Js Registrations","An Omniture site metrics term. The number of completed jobseeker registrations in a given reporting period.",
"12cf7f51-49ef-4447-ba2a-e150fdcb043a","Oauth","OAuth is a protocol used to authenticate clients (advertisers/third party partners) against the SEEK APIs (e.g. Application Support and JSP APIs).",
"1392f089-b923-472a-bdb8-7448289fb475","ASU","For more information see ASU Phase 1 Jive page.","Advertiser Site Upgrade project"
"1a2cc243-0905-4dbd-8d17-27923ff0fc6e","Haskell","Often used as a comparison by other functional languages given its strictness and purity, has a very academic focus although there has been some business use. Haskell developers generally have neck beards and several PhDs after their name, their code inspires fear and awe in the rest us mortals.",
"1b4c5f6d-2612-4777-acfc-88383ea4271c","WAF","The WAF actively blocks people it detects as attacking the SEEK Employment website (as of August 2011). Refer to the Security team for more information.","Web Application Firewall."
"20272ef5-24d0-42c3-8f7f-000bed03b212","Opportunity","An opportunity is created within SAP CRM by Sales (it is similar to a quote) and is converted to a contract once the advertiser has agreed to it.",
"21eec32d-6ead-42c4-86cf-9e0a30880edf","BP","Business Partner - See CRM - Create a BP hierarchy Jive page","Business Partner"
"22287fd4-a3da-4c78-8412-8fba39ed5c3f","Lemmatization","The mapping of a word to its base form and / or all its other inflectional forms, such as: singular or plural for nouns tense and person for verbs positive, comparative, or superlative forms for adjectives. For example, a search for “car” will get documents containing “cars” as well. Stemming is different in that it would get documents containing words starting with “car” i.e. “cared” or “career”. Lemmatization is used by SEEK's FASTCloudview search engine when a jobseeker is searching for a job.",
"23ef6017-20a1-4fc6-97fa-4382103bd71b","SANTA","Single front door Activation and Nation fix for the new Advertiser Centre. (7 November 2012)","Single front door Activation and Nation fix for The new Advertiser centre. "
"2c6746a1-faee-463b-9990-4abfa7decda7","NAC","Also known as Pacman, or Talent - SEEK Advertiser Centre (talent.seek.com.au) in contrast to the old advertiser centre (OAC) (advertiser.seek.com.au). The New Ad Centre, launched October 2012 and the project name was Pacman (Position And Candidate Management) in the Advertiser stream. All Advertisers have now been migrated from the Old Advertiser Centre (OAC) (advertiser.seek.com.au) as of Oct 2016 and it's now just called the Advertiser Centre. It is the SEEK platform hirers use to place their job ads, track and manage candidates, and review job applications. The NAC is a great platform thats makes it much easier for hirers to manage the hiring process.","New Ad Centre / New Advertiser Centre"
"3067360e-a788-46bd-bc79-224fdcb347ba","Integration","Usually refers to Biztalk – which integrates the website with SAP. Also means the point where code is merged from earlier projects into later projects",
"30dbde00-9f20-4f18-ae74-753f602d9e5c","Upkeep","Internal tool at seek used to compare how up to date teams SKU toolkits are. See SKU.",
"3934b1e0-8542-4cba-a0e2-be6a917bb915","ASP.NET WebForms","Microsoft's answer to replacing ASP, still widely used but again seen more as an anachronistic approach to web development",
"3a171e0b-0002-46f4-98cc-cf1bd12a9506","Hobbit ","A search algorithm which has since been renamed to SmartSearch.",
"3b46b8b9-035f-4b4a-85f9-e89d6f546f6a","SAP","SAP stands for Systemanalyse und Programmentwicklung (System Analysis and Program Development). SEEK uses SAP to manage it's customer's data (CRM), finance (R3/ERP) and reporting information (BW). SAP was implemented in 2007 under the BOOST project.","Systemanalyse und Programmentwicklung"
"3e479361-261a-4074-88b3-cfe4be88ae78","Visit Length","See also Average time on Site",
"426945b8-8228-4ac0-8259-c1276342d14d","SCALA","A multi- paradigm language that runs on the JVM, it's a functional first, OO second similar to F#, a great language to transition to from Java or C# - used by some well-known companies such has Twitter or LinkedIn",
"43bbb461-1a19-41de-bd07-7f78de22aad2","C#","Microsoft's flagship programming language and what we predominately use at SEEK – whilst it was looked down upon as a Java wannabe it has now surpassed Java in many ways.",
"481a9dca-71e3-4acd-8c25-bc6c09c7b98f","Stats Manager","A service that collates and aggregates the output of Stats Logger and bulk inserts it into the SeekWeb database. See also Stats Logger Investigation",
"482f1af7-18dc-4471-a7da-e455fe8097c0","BW","Converts SAP data into a flexible reporting solution","Business Warehouse"
"489223a9-76e6-4795-90cf-47aae640cb0a","TOC","They are the guys that look after your pc, laptop and phone. If you have a problem or request about hardware/software then you contact TechOPS.","Technical Operations Centre. Also Ops"
"4fb6d875-933b-4432-82f9-048315214785","FLD","An outline of how the SEEK Learning leads can be distributed to the sales staff in a more efficient manner.","Faster Lead Distribution"
"5073c78f-603c-4d24-9736-615ba30b26bf","ET","Exact Target is a cloud-based Campaign Management service that acts as an email gateway for emails that are sent to Jobseekers (e.g. New registration emails and JobMail).","Exact Target"
"5074ad08-f9c0-449a-bc7c-6e110994212c","Enhanced Ads","Enhanced job Ads, also StandOut Ads","Enhanced job Ads"
"5382f89e-cdc6-47ae-b259-d2f404ef7702","Config Engine","A legacy in-house built component designed to deal with the initial inadequacies of the .NET framework.  It uses configuration files to determine the look and feel of sites, it intercepts all calls to the website. See the jive page for more information",
"552b235e-8466-4674-9107-78c19a4e285a","LISTING","A Listing is the classification level of detail of a job.  A job has one or more listings e.g. a dual list job will have a listing in main and exec",
"57098c73-aecb-4784-88fc-4112116d2e91","Orchestration","A Biztalk term that means to  execute a series of steps. Orchestrations in biztalk are the steps which manage data passed between SeekWeb and SAP",
"57602b88-f155-4afd-ad8b-a7433199354f","MAIN","The Australian SEEK website  (www.seek.com.au) also referred to as AUSMAIN or SEEK Blue as it makes up the main market segment",
"588be040-8342-483e-b339-2426a360d83a","SUK","See http://wiki/mediawiki/index.php/SEEK_UK_Repositioning","SEEK UK repositioning"
"5f8e3533-cd2d-472d-9f3a-70d1cd038be2","CopAJA","Copy a job ad.","Copy a job ad."
"693aebcc-31dd-42e1-91ee-c605b60042ac","UB Frequency","A Nielsen/NetRatings site metrics term. The Omniture term is Return Frequency. The unique browser frequency metric represents the average number of times a Unique Browser returns to a site during the reporting period. This is calculated by dividing the total sessions by UBs.","Unique Browser Frequency"
"6a695d53-7d91-4b18-84fa-3677415eda42","Revenue","Revenue is what is recognised in our Profit and Loss statment. There is a difference between what we bill the customer and what is in the P&L statement. e.g. We may bill a customer upfront, but not provide the service until a later date. Once the service has been provided we are able to report the billings as revenue.",
"6c90601e-9908-4ef1-ba2c-b1bfedefd3d0","Time Spent On Site","(also Total time and Eyeball minutes) (An Omniture site metrics term. The Nielsen/NetRatings term is total time). The total amount of time (in minutes) that visitors spend on a site in a given reporting timeframe. The time spent on the final page of every visit is not capturable by Omniture. This is known internally as Eyeball minutes.",
"7199574d-8d57-46ee-bf63-c422bc650b59","GUID","A Globally Unique Identifier is a unique reference number used as an identifier in computer software. The term GUID typically refers to various implementations of the universally unique identifier (UUID) standard",
"71df8593-8ed3-45cb-a75e-199ef6d9bfc6","AE","A type of Sales Rep that manages large volume customers. Phone based Sales account managers in the Melbourne office","Account Executive"
"73103719-bad6-4a3c-a44c-13bd64f65dee","AMI","A special type of virtual appliance that is used to create a virtual machine within the Amazon Elastic Compute Cloud (EC2). It serves as the basic unit of deployment for services delivered using EC2.","Amazon Machine Image"
"73ba6bc2-ad11-4af3-beaa-2ea73598a755","MVP","A product with just enough features to satisfy early customers, and to provide feedback for future product development","Minimum Viable Product"
"7564a828-7165-43b6-ae08-e7269b05a170","Market Segment","A concept for grouping listings e.g. Market Segment 1 is known as Main, Market Segment 2 is known as Exec, Market Segment 3 is Campus, Market Segment 4 is IT, Market Segment 26 is Healthcare. There are others but most of the functionality relating to the others is now legacy e.g. Adecco",
"77f0540a-c586-4d34-aeb8-abf9e190278e","Average Session Duration (also Average time on site)","A Nielsen/NetRatings site metrics term. The Omniture term is Average time on site. This shows the average length of a User Session (up to, but not including the final page viewed). This is calculated by dividing the total of the Page Durations by the total number of User Sessions. The time spent on the final page of every visit is not capturable by Nielsen. True time is calculated by the Hitwise Average Visit Time reports.",
"7934a611-6b74-4370-94dd-d84664c12780","EBB","AWS Elastic Beanstalk is an orchestration service offered from Amazon Web Services for deploying infrastructure which orchestrates various AWS services, including ECSSimple Notification Service, CloudWatch, autoscaling, and Elastic Load Balancers.","Elastic Beanstalk"
"7b01d189-8f23-44f1-8386-f64df1f720ee","Talent","Talent is the name of the new advertiser centre (2013) https://talent.seek.com.au . It is a product of the Pacman (Position And Candidate Management) project within the Hirer stream.",
"7b098ae7-6317-4ce5-b616-d3bcafeab79c","CASBA","Create A SEEK Business Ad. This SEEK Commercial project is designed to allow businesses to list their ad automatically, in a similar manner to CAJA.","Create a SEEK Business Ad"
"7de2c816-1e09-4ee3-981f-b7e1c7c25bc7","Seek Native","The standard application process on SEEK. using the SEEK application form -  a candidates details are emailed directly to the hirer. See also LinkOut ",
"85f3e394-b040-48c9-ba6e-5223f489e30e","SAE","A feature where candidate data can be retrieved on demand directly from SEEK's webservers. See SEEK Application Export business process jive page. The following information is retrievable through SAE: candidate contact details (first name, last name, email address, phone number) plus the Seek JobseekerID identifier if the candidate was logged in when they applied for the jobjob application attachments: resume, cover letter, selection criteria documentscandidate screening questionand answers (if applicable to the job advertised)","SEEK Application Export "
"884182a3-8db5-42b2-90d3-b48eb5328665","Visits","(Omniture site metrics term. The Nielsen/NetRatings term is Sessions.) A visit occurs when a visitor comes to and navigates around your web site. A visit may consist of single or multiple page views. The visit persists until 30 minutes of inactivity or 12 hours of continuous activity.",
"8894f948-9b14-4bb4-a480-ae753fc6605c","Copy","A small piece of text, such as a sentence, a phone number, or an email address that can be displayed on the site.",
"894ea7e2-f8b8-48a7-96c6-ae2bda1a2a63","Total Sessions","A Nielsen/NetRatings market intelligence measure. The total number of times UBs visit a site, having left for more than 30 minutes,  during the reporting reporting period. Equivalent to Average 'UB Frequency' times UBs. Also known as visits in other tools.",
"8c1f5dd7-b2e0-427e-a9bf-275696684f94","Applications Completed (NON LINK OUT)","An Omniture site metrics term. The number of completed job seeker applications for non-LinkOut scenarios only.",
"8df75a64-9017-4a23-87de-8fd9cf8f1f32","SEK 1,2 or 3","SEEKs customers are classified as SEKSEK2 or SEK3 customers. SEK1 are SME Customers SEK2 are generally large subscription and pack customers and are fully maintained by the Credit Controllers SEK3 are small to medium subscription and pack customers",
"97a042dd-928a-4c45-a75d-63869ad86600","SmartSearch","A search algorithm previously named Hobbit.",
"990faa54-820e-4bc5-a91f-806633a18793","C Sharpers","Developer project team from 2010",
"99565395-51e0-4788-8e62-3d7fa21173ef","SKJ","SEEK jobs.  Usually used in conjunction with SKL (Seek Learning).","SEEK Jobs"
"9af404e4-2321-44ff-84f8-6da90eca58d0","Average Visit Time","A Hitwise site metrics term. The elapsed time from the first to the last page request that constitutes a visit, adding the average time per page for such a visit. Includes time spent on final page of visit and hence more accurate than Nielsen//NetRatings Market Intelligence",
"9dacb2aa-57b9-4968-8481-0d98b556e4bc","PII","Personal information in the context of security and privacy laws.","Personally Identifiable Information"
"a059968e-bfb2-4009-9d13-10d2f916f92c","Job Application","An application for employment made by a Jobseeker for a particular Job Ad on SEEK. See Job Apply flowcharts on Jive",
"a115feb8-d723-49ec-95fc-2d63fc849318","Overad","Any Ad(s) that exceeds the contract amount e.g. If an advertiser has a contract for 100 jobs per month and advertises 120 jobs during a particular month, then the 20 OverAds will be charged at the existing contracted per ad rate.   Note: Prior to there was an OverAd rate that applied to ads that exceeded the subscription amount by more than 10% - this no longer exists.",
"a63ab97b-d8a7-49f3-91b2-2ffb26275559","Saved Search","Jobseekers can save their frequent job searches to the SEEK homepage, when they are logged in",
"a91cbd47-9a6f-4078-aa25-1a6f05457477","Search Location","An Omniture site metrics term defined as the location/s selected in job searches.",
"aa3638cc-a4c5-461b-9477-e0ce7265494c","AQTF","Is the national set of standards which assures nationally consistent, high-quality training and assessment services for the clients of Australia’s vocational education and training system. The revised version of the AQTF is effective from 1 July 2010' http://www.training.com.au/Pages/menuitem91cdbaeb7a2bc0e2cd9ae78617a62dbc.aspx","The Australian Quality Training Framework "
"ac91c15f-cad2-40a6-8437-b87f094cd485","Unique Visitors","An Omniture site metrics term. The Nielsen/NetRatings term is Unique Browsers. A visitor is a web browser (i.e. a computer's interface to the web) that accessed your web site.Unique visitors represent the number of unduplicated (counted only once) visitors to your website over the course of a specified time period. A unique visitor is determined with cookies. Unique Visitors are unique to the reporting period and cannot be summed across reporting periods or sites.Unique Visitors do not equal  'a person' as multiple people can access via the one PC/browser or  a person may use multiple browsers ( from home and work) or may delete cookies.",
"af4e61cd-674a-4acc-a6a0-08bf1f059ab3","XCAJA","Express CAJA is a cut down mobile-only version of the Create a Job ad process on the SEEK Talent website. This product launched in Oct to SME Direct Hirers who are new to SEEK. See Caja and Express Caja","Express Caja"
"af677ef0-7fdb-4c27-99e1-9d81ab745a9e","Omniture","A third party company that allows web analytics of user behaviour on SEEK’s websites.",
"b0b0033a-ea53-4283-b20c-188c471b7c64","AdAPI","AdAPI was a project in 2012 to support the API requirements of the Pacman (Position And Candidate Management) project.",
"b19b1dd6-faa6-4dfa-aa83-b85d45623307","JAG","The technical Architectural Community of Practice at SEEK. Meetings fortnightly and it aims to build greater shared understanding, support and alignment in the architectural choices made between and within teams at SEEK.","Joint Architecture Group"
"b5892b55-0673-4758-8022-53e28aa8ed7d","JSU","Job Seeker Update was a project to replace the Config Engine with the MVC framework on the jobseeker website.  See JSU project","Job Seeker Update"
"b71e43dc-2147-4ae3-981c-fb7669e52a9a","SEO","Search Engine Optimisation is the streamlining of the SEEK Website to ensure it has a high prominence in search engines such as Google, where organic searches (i.e. non-paid) are sourced","Search Engine Optimisation"
"b7f1cb73-b063-44ed-89d5-4f598985f4ad","POC","Proof of concept is a realization of a certain method or idea in order to demonstrate its feasibility, or a demonstration in principle with the aim of verifying that some concept or theory has practical potential.","Proof Of Concept"
"b7fa4ebe-e9d8-4aa7-bb2c-38ec29ba7b46","Seek Toolbar","SEEK had an Internet Explorer toolbar that could be downloaded from the website. It allowed you to search for jobs straight from the web browser. The link to download this toolbar was removed from the site in October 2009.",
"b957a507-c83e-4620-a51d-b915d60835aa","SOL","Swinburne Online. A joint venture between Swinburne University of Technology and SEEK. Established in it provides students with a Swinburne University degree, with programs delivered online via a collaborative and interactive learning community.","Swinburne Online "
"bb665ba1-1807-4fba-8f3a-ab8cfa8f35d5","ROT","Remove Other IT skill. An enhancement to remove 'Other' from the skills classification in IT. PRN20138.",
"bb6bfbf5-4099-442f-a2e4-a2fe9effdb50","RENEG","Renegotiation of a contract which should occur prior to the expiry of the current contract. See Renegotiating an opportunity","Renegotiation"
"c328db33-cfe9-462b-ad7b-4130b03fa1b2","Stemming","The use of linguistic analysis to get to the root form of a word. Search engines that use stemming compare the root forms of the search terms to the documents in the database. See also Lemmatization",
"c46d3850-b2ec-4822-bfb1-e59e3bad623b","Web Service","From W3C, A Web service is a software application identified by a URI, whose interfaces and binding are capable of being defined, described and discovered by XML artifacts and supports direct interactions with other software applications using XML based messages via internet-based protocols",
"c527a843-f3f9-496e-b792-911202e3b2a8","AWS","A subsidiary of Amazon that provides on-demand cloud computing platforms to individuals, companies and governments, on a paid subscription basis","Amazon Web Services"
"ccb0a388-0df9-41fb-858b-fae270efaf92","Seek Main","SEEK’s main website www.seek.com.au",
"d37de56a-8a0a-4473-9ba7-538e4d81c954","SIM","SEEK Inventory Management (See IM)","SEEK Inventory Management "
"da9f7271-9081-48a7-8ffb-4fd0f399bf76","Proactive reach","Corporate hirers want us to do more when it comes to minimising the time and effort to identify new potential candidates. This is an ongoing area of importance of the Talent Search roadmap and focus areas. ",
"db62b0dd-14aa-4d30-b870-a17e91aafa50","Pacman","See NAC",
"dd5352e0-bded-42cb-87ae-36bcc9d6890d","PROFIT","This forum prioritises project and work requests for IT where the cost is over \$50,000","PRioritisation OF work for IT forum"
"df4219fd-fdc0-46af-a507-f5b231f35892","Search Work Type","An Omniture site metrics term defined as Worktype/s selected in job searches.",
"e3518f8a-be06-4917-8b12-8fc93030fd83","Industry Pages","Pages on the site that are setup for an industry eg for accounting jobs the page would be http://seek.com.au/accounting-jobs These pages have targeted advertising and allow us to guide search engine traffic to relevant pages.",
"e4ee3ee4-7293-4af3-bfc1-b7e03d9b779a","Advertiser (HIRER)","The term advertiser (when used as an all encompassing term to include 3PUs, Agents, Recruiters and standard advertisers was replaced in 2013 by the term Hirers) There are 3 types of Hirers : SME  - casual hirers that purchase job ad packs Recruiter -  they have contracts & ad packs and have 6 months to use these ads (this is the same for Job Ad Packs). Corporate -  corporate hirers buy a block of ads e.g. 50 Ads/month and are charged an Over-Ad rate if they use more than they have purchased.",
"e8647eb1-783f-4341-9b14-341a9424321d","AJAX","Rich media technology for dynamically changing content on web pages based on user action, page action, etc.","Asynchronous JavaScript and XML. "
"e8ee0682-38d4-4d61-91e1-4059db8568a8","Sub-Classification","Each job ad has a Classification which is an industry (e.g. Accounting, IT) and a sub-classification or specialisation within an industry (e.g. Accounting > Accounts Payable, IT  > Architect). In our classifications went through a major update with the TAXI project.",
"e95067e0-718a-4a15-9726-f78cec38d4b5","DTO","Data Transfer Objects are used to transfer data between software applications. ","Data Transfer Objects"
"e9994ed4-05a8-4390-ae90-46879a26b2e7","Native Application","A Job Ad that uses the standard SEEK application process to capture Job Applications. This is opposed to a LinkOut ads",
"ef4b33b3-8a84-4999-a1c1-09456a1c7eed","WSDL","Stands for Web Services Description Language, is written in XML, is an XML document, is used to describe Web services, is also used to locate Web services and is not yet a W3C standard.","Web Services Description Language"
"f065e0f1-dd5d-4197-a874-9a001df4a6ab","AdLoader","Refer to 3PU",
"f1e8e081-e967-4ff6-a1a3-aada95d3c2b8","Return Frequency","(see also UB Frequency) An Omniture site metrics term. The Nielsen/NetRating term is UB Frequency. The number of days between repeat visits from your visitors.",
"f3aab74d-6a63-4e12-8f72-03641f5d6684","Credit Hold","When the Credit team has placed a hold on an advertiser's account because of overdue/unpaid accounts. This prevents access to many features of the site for that advertiser.",
"f4ac01a6-f177-4b78-9299-4e8a385b1b75","FAT","A project to add a formatting toolbar to the CAJA process to provide basic formatting to hirers while creating a job ad.","Format Ad Toolbar"
"fa4c9da5-8c19-48a5-8f90-ae85b5f159e7","SEI","The SEEK Employment Index (now known as the SEEK Employment Report) represents the relationship between demand for workers and jobseeker activity. When the Index increases, it demonstrates a 'tightening' employment market; where advertisers find it harder to fill roles (i.e. demand outweighs supply). This is favourable for jobseekers, as job opportunities are greater and competition between applicants is reduced. Inversely, as the Index falls, it demonstrates a 'softening' employment market (i.e.supply outweighs demand) and advertisers find it easier to fill roles. In this instance, jobseekers need tocompete for the available jobs. It was developed in consultation with Victoria University's Centre of Strategic Economic Studies. See - SEEK - SEEK Employment Report","SEEK Employment Index"
"fb9a17c5-b9a0-4fd3-bd8b-a2a7fd23e89e","F5","A project that changed the look and layout of the home pages for AU, NZ & UK (3 phases, last phase completed in 2009). See http://aumel-intra:82/PWA/F5/_layouts/viewlsts.aspx",
"fdf36f83-d2e9-46b9-a88d-2a1c04936332","JAC","Job Apply Confirmation email that is sent to the Candidate after they apply for a job","Job Apply Confirmation"
"00498c33-bd34-4ee7-8ac7-c915109bc810","PCP","Prior Comparison Period (a finance term) e.g. May-13 vs May-12. In data terms – this means comparing metrics for the current period of time against a prior period of time.  This might mean sales this year to date vs sales last year up to the same date, or last quarter against the quarter before that. Whatever the comparison, PCP generally refers to a similar period of time.","Prior Comparison Period"
"007a7bf9-90a6-47e8-959a-e82054d7726b","HSM","A hardware security module (HSM) is a physical computing device that safeguards and manages digital keys for strong authentication and provides cryptoprocessing. These modules traditionally come in the form of a plug-in card or an external device that attaches directly to a computer or network server.",
"01791498-34f2-49f9-8838-17154b9ebdc6","Site Searches","(An Omniture site metrics term.) The number  of job search results pages viewed in a given reporting timeframe. Is not reflective of the unique search instances.",
"0454ede8-bb9b-4b36-a7d8-c8f304ca1dea","LEGO","LEGO (the acronym has no meaning) was the first agile project in the Advertiser Site Upgrade programme of work. It commenced in August 2011.",
"0b7c5e1d-9ad8-4984-9621-66ad4aecf224","Referring Domain","An Omniture site metrics term.The Nielsen/NetRatings term is External referring domains. The domain your visitors came from to access your site. Requires user to have clicked on a link to your site from the referring site.",
"0c386aad-928e-48c6-a01b-55d1d04ae777","Channel","A legacy term that refers to site/market segment eg channel id 4 is IT",
"0f7a5668-554f-4d11-a26f-e35f359fbec4","Screen","Part of the Job Apply process. It was created in 1999 to allow advertisers to screen job applicants via a number of questions e.g. Do you have a driver’s license?. The Screen page is the first page that displays after the jobseeker clicks Apply. The purchase of Screen is optional. See How to add a common question to screen",
"1041bfee-31a9-4ead-82bc-244a08a03154","Calling Out Contract","The method used by SAP when a job ad is posted, to decrement this job from an ad pack or subscription, (or to charge for a casual ad if there is no current ad pack or subscription)",
"144ea372-3979-4852-ae18-862a184ee5b3","URI","A string of characters used to identify the name and/or location of a resource.","Uniform Resource Identifier"
"16e05d54-feca-4627-bf41-55ae4a648c02","Graduate","A graduate/entry-level job covers apprenticeships, traineeships, cadetships and other junior roles.",
"18100d4e-0fe6-47a1-8be0-9c8c354b1356","Small Change","SEEK's charity giving program that is matched dollar for dollar by SEEK.",
"18d034f6-a5dd-4b53-a4b3-ee44376f8dcc","Ironport","Ironport is the hardware device that we use to send and receive emails securely. Note that this has been superceded for some Website emails e.g. JobMail and Jobseeker registration. For more information contact the Systems Engineers in IT Ops.",
"1961fc7d-1db8-409c-8bdd-e4d95d293496","RFC","A Request for Comments is a type of publication from the technology community, that requests comment from the broader community in the forming of standards.","Request For Comment"
"199f7f22-0bb9-4191-891f-5da563b39b91","JLO","This project (commenced in August 2011), involved the creation of a mini site that third party uploaders (3PUs) and advertisers can access to purchase JSPs (if they don't have access to the Advertiser centre). See The specified item was not found.","Jobseeker profiles Link Out"
"1a1bc567-0c74-4b2b-a23f-b11b5a34fca3","Job Application Data","The initial response to the initial request (after Authentication) in the SEEK Application Export process returns the Job Application Data. This includes Contact Details, reference data about the Job Application and URI’s to any attachments.",
"1caf917c-7379-4dde-a312-24b7802810b5","WURFL","Pronounced Whirr-full. It's the replacement for the Mobile Device Browser File (MDBF) that extended ASP.NET's built-in mechanism for exposing metadata about a mobile device's capabilities. http://wurfl.sourceforge.net/Some kind souls have thrown together a .NET API to wrap it, and that's what we've now put into the JobSeeker site. We have the source code and so can theoretically make additional changes.  One change that was made by Support was so that we can use relative instead of absolute paths inside the WURFL.xml.config file when referring to the path of the WURFL xml data file, and the path of the patch file","Wireless Universal Resource File"
"1cc4910d-aa45-48d1-9b61-17fbc2a8be1f","Onsite","Onsite companies have a SEEK job search on their website that looks like their website. When searching for a job on their website it queries our database e.g. http://www.jobs.adecco.com.au/ - ADECCO and http://www.rdns.com.au/CORPORATE/CAREERS/Pages/Current%20Vacancies.aspx  - the RDNS site.",
"1d98ff41-d8d5-48db-9f82-faea1805fecc","GDPR","A regulation in EU law on data protection and privacy for all individuals within the European Union (EU) and the European Economic Area (EEA). It also addresses the export of personal data outside the EU and EEA areas. The GDPR aims primarily to give control to individuals over their personal data and to simplify the regulatory environment for international business by unifying the regulation within the EU.","General Data Protection Regulation"
"26b22a41-d1b7-418e-a079-00833262ec1c","FLAPI","An Engineering Stream API replacement for Fastlane Plus - see Job Posting API (FLAPI) for more information",
"2c74577f-c53a-4dc6-a50a-b866071bd1e5","Stats Logger","A service that records the list hits (when a job appears in search results) and detailed hits (when a job’s details are viewed).  These stats are used primarily on the advertiser centre pages and flow to BW’s APR (Ad Performance Report). See Stats Logger Investigation",
"2e9d8f94-b561-4ea9-a3de-5237fc6a077e","Fastlane","An alternative to CAJA. The advertiser fills out a spreadsheet (one row per job). This outputs an xml file that goes to the upload page on the website and is synchronised with our database.  See Fastlane Plus Project (Bulk Imports)  for more information. Fastlane Plus is currently being replaced - see Job Posting API (FLAPI) for more information",
"32fad58a-42a9-451a-80e1-2a3533efb061","Referring Url","An Omniture site metrics term. The Nielsen/NetRatings term is External referring URLs. The URL (or specific page)  your visitors came from before they were on your site. Requires user to have clicked on a link to your site from the referring site.",
"34fe5172-ce7c-42bd-a3d5-053acb93f85d","XXE","A type of attack against an application that parses xml input. This attack occurs when xml contains a reference to an external entity. It is processed by a weakly configured xml parsed.","XML External Entity"
"35428bc4-6954-4ce9-9950-86a1ce4b4b9a","PA","Premium Ads are ads that are highlighted in yellow and appear at the top of a job search list. There are only two Premium Ad slots per classification, sub-classification and location. For more information see \","Premium Ad"
"37e506ad-ca71-445a-98bf-86c7db73cfb4","MSO","All ads are automatically upgraded from Classic to StandOut for any Hirer with an MSO automatically ","Mandatory StandOut Pack"
"3809b7f0-25e6-4d11-9c6c-e713d813e875","SO","Small and Medium Enterprises e.g. A small accountancy firm with 3 employees","Sales Opportunity"
"393a8829-9ee2-42a5-8da1-90c4ea8fdc12","UAT","Testing performed by users to verify that the system works as planned","User Acceptance Testing"
"3b82a505-2a00-40ab-9a6b-9b09555dba97","Application Starts","An Omniture site metrics term. The number of 'apply now' clicks for both LinkOut and non-LinkOut ads.",
"3cb48f75-0270-4364-bdcb-4bde2aa5289a","Search Sub Classification","An Omniture site metrics term defined as the sub-classification/s selected in job searches.",
"4072cac2-7512-45c5-a221-3d9d42b80da7","SKL","www.seek.com.au/learning","Seek Learning"
"47054840-08e3-479f-bc37-8a67eb6ccab7","FAST CAJA","A page within SMART that compresses 3-5 pages to 1 page to allow Customer Service to enter the job details for an advertiser quickly.",
"4d20f8aa-7e75-4e43-ac43-eac54e0e18cd","Attack Surface","The attack surface of a software environment is the sum of the different points (the 'attack vectors') where an unauthorized user (the 'attacker') can try to enter data to or extract data from an environment.",
"4e4d7d0e-8b89-4682-860d-847841b8b9b9","MAX/MAX","Refers to roles where candidates are highly skilled and in short supply, and are therefore ‘picky’ about the role they are searching for (e.g. looking for the best salary, working conditions, career progression prospects, etc.). In Max/Max, advertisers are also picky – they only want to hire the best candidate for the role. Rather than looking for ‘just anyone’ who can fill the role, the advertiser is looking for a candidate who meets a wide range of specific requirements, which may include hard factors such as qualifications and experience and softer factors like cultural fit, values, etc. Max/Max or (Max-Max or Max Max) roles are often found in specialist fields. Example Roles: Geologists, User Experience Experts, CEOs",
"4f0d1968-c9ab-4c2f-b5cb-838dcd22c754","ERMS","Email Rule Management Service (SAP)","Email Rule Management Service (SAP)"
"502df150-b2f6-4ba4-8abe-9dd0947e649c","Bounce Rate","An Omniture site metrics term that shows the percentage of visits where the visitor enters and exits at the same page without visiting any other pages on the site in between. (i.e. % of Visits which are single page visits)",
"52a19423-ad1a-4621-924f-8741cc6e11f6","Return Visits","An Omniture site metrics term. SiteCatalyst report that shows how many individuals have visited more than once since SiteCatalyst began tracking your site. These visits are not for a specified time, but are all those that have viewed your site once and have then returned.",
"5422be86-fa4d-4ba8-8900-60436eb7ad2d","PRN","The PRN is generated by Online when an Advertiser pays by credit card. The PRN is sent to Westpac and then included in the CAF file that is returned to SEEK to allow payments to be cross-referenced in SAP.","Payment Reference Number"
"5607072b-f71c-4ed4-a998-339b9b82bbe0","CMIS","Commercial matches in SEEK","Commercial matches in SEEK"
"560ce41b-ca6d-43a3-b019-f430680938d3","ESOS","Education Services for Overseas Students. See http://www.aei.gov.au/AEI/ESOS/default.htm",
"572a8227-98c9-4423-ac02-d6a0519e1657","SOA","From wikipedia: Service-oriented architecture (SOA) is a style of software design where services are provided to the other components by application components, through a communication protocol over a network. The basic principles of service-oriented architecture are independent of vendors, products and technologies","Service Oriented Architecture"
"592773f5-697f-43c1-ba8a-b00d1aa1b45b","Page Views","(see also Page Impressions) Omniture site metrics term. The Nielsen/NetRatings term is Page Impressions. A page view occurs when a visitor accesses a page on your web site. A Page View is recorded each time a page instrumented with Omniture code is displayed in a user's browser This will occur whether the page is served directly from the web server, from a proxy, or from the browser’s cache.",
"593121fb-8acd-43aa-a992-040ac5194511","OKR","Objectives and Key Results is a process for setting, communicating and monitoring goals. e.g. Objective: Improve customer satisfaction. Key Result: Improve NPS from 5.0 to 8.0.","Objectives and Key Results"
"594863a6-c017-43de-ae03-5be51e89f872","Badword Scanner","The badword scanner is a service that runs approximately every 15 minutes on the SEEK website as part of SEEK's @Compliance process. It scans all live ads for offensive words; adult industry phrases; known fraudulent email addresses; known fraudulent phrases and known fraudulent advertiser names. If an ad is found to be non-compliant it is removed from the site and sent to the Non-compliant holdings queue - for more information see Compliance and Complaints",
"5c40e5cd-40b0-48f2-92af-da59bad8d552","Clojure","A functional language that runs on the JVM, a Lisp dialect, and often takes hold of developers who speak of it in delirious joy and fervour. It's the programming language equivalent of a cult.",
"5ca3f7d1-8899-4274-92a4-9f42e2a2a7bb","Standout Ads","Written as StandOut ads and also referred to as Enhanced Ads during the development phase.  They have 3 additional bullets and the ability to have a customer specific logo and has differential pricing between recruiter and non-recruiter advertisers. See StandOut Ad project 2007",
"5d1dbb8c-c33c-4717-8b7c-ddf4796f7cbd","MVC","Model View Controller is an architectural pattern which isolates domain logic from input and presentation (GUI), permitting independent development, testing and maintenance of each. A pattern, or more typically a framework, to provide a way to organise code in a more maintainable structure. The model refers to the data, the view the presentation or interface and controller to string them together","Model View Controller"
"6126f975-6988-432a-ab6d-2ae977d4f30b","RDS","A scalable relational database in the cloud. It provides cost-efficient and resizable capacity while automating time-consuming administration tasks such as hardware provisioning, database setup, patching and backups.","Relational Database Service"
"63660d0c-69ff-4066-94e7-01f6e4e3589c","MAMS","Master Agency Media Service (Government)","Master Agency Media Service"
"6458de7e-cde4-4e1a-8332-c756da387fe8","JORS","Jobsearch Relevancy Survey. This is a question on the job search results page, and the job details page, that asks the jobseeker if they think this job is relevant. See image below",
"6517df01-bf93-4a75-a398-9500d6939893","OAC","Old Ad Centre, also called Old Advertiser Centre or Advertiser Centre (advertiser.seek.com.au), it has been replaced by the New Ad Centre (NAC) talent.seek.com.au. Clients are still being migrated from the OAC to the NAC. For more information see the Pacman (Position And Candidate Management) project.","Old Ad Centre"
"66cee40f-ec27-43b0-ae8e-d93926de97a2","Seek Blue","SEEK’s main website www.seek.com.au. Also SEEK Main",
"6830859f-bbdd-47e8-a719-99eef99af896","ASP","Old Microsoft web site development technology - you should view with apprehension anyone who still professes to use this, and outright suspicion if they actually like it.","Active Server Pages"
"695eaa6c-6df7-423a-86db-961abe94261b","SME","e.g. A small accountancy firm with 3 employees Also : Subject Matter Expert – a person who is an expert in a particular area","Small and medium enterprises"
"6b64845c-4955-4d6a-a3d0-8294d80b9788","Domicile","At SEEK - determined by the country of the contact address of the Advertiser.",
"6c65d070-19bb-4e63-a367-1f1147803922","CS","Customer Service department","Customer Service"
"6d7bbe1d-84cf-4111-8544-f26ebb0f8bfa","Path Length","An Omniture site metrics term that shows you, by percentage and by total count, the depth of each visit to your site. It indicates how many pages the average visitor to your site views before leaving",
"6e3f59d6-2585-452b-a629-a140ee6f3aec","Total Time","(also Time spent on site) (A Nielsen/NetRatings site metrics term. The Omniture term is Time spent on site). The total amount of time, reported in thousands of seconds, all UBs spent on site in the reporting period. This is calculated by multiplying Page Impressions (PI) by Average Page Duration (APD).  The time spent on the final page of every visit is not capturable by Nielsen. To understand true time, refer Hitwise Average Visit Time reports.",
"71611f48-ef7d-4789-af3d-e4313dd8836c","Search Terms","An Omniture site metrics term defined as the keyword/s used in keyword searches.",
"7285cf95-4509-414f-845b-a452d0e9be3b","Dequeuer","The SEEK Learning dequeuer is a .NET console application, written in VB.NET, that processes registrations from the LeadQ & sends to the BOOST integration layer webservice.",
"7287b5a2-8dc9-435e-9b18-108d6a8b0d56","Candidate Management","Advertiser centre tools for allowing advertisers to contact and reject applicants and also forward application details to colleagues [mainly ASP code]",
"73fe00fd-83fb-453d-8285-b7c1210922bb","MAJA","See http://wiki/mediawiki/index.php/MAJA_Mirror_a_job_ad ESM-Government and Healthcare have their job ads mirrored (copied) for free. e.g. A federal government accountant job that is created under the Government/Defence classification is mirrored under the Accounting classification. When a job ad is mirrored there are two separate JOB IDs each with their own LISTING IDs (unlike DUAL-LISTED ads, where there is one JOB ID and two LISTING IDs).","Mirror a job ad"
"77b86a1f-f22f-47cd-91c4-2d2f94fc7e14","JAPU","Job Apply Profile Upsell (as part of the JSP project). When a jobseeker applies for job, they are prompted to create a profile, if they haven't already done so.","Job Apply Profile Upsell"
"7c20f0c7-dbcd-4015-8f37-6fc0aaed6732","Junction Points","Jobseeker Profiles - JSP   was also the name of the Jobseeker profile project which replaced the old Resume Search application. It allows storage of jobseeker resumes and profiles.  It allows advertisers to head-hunt jobseekers using the details they have stored.",
"7d557ae1-717c-49c8-a143-e1f3aefa1645","JDP","A page that contains details of a job (e.g. after a Candidate clicks on a specific job from the search engine results page)","Job Details Page"
"7f249013-f843-40ce-87c5-9bd56e336183","EAJA","Edit a job ad process - see CAJA and EAJA flowchart Jive page","Edit a Job Ad Process"
"809445c1-2438-4bd1-874f-d36ef1a5b5fd","Dual-Listed Ad","An ad that is created in Main and Exec, or Main and Graduate, during the Online CAJA (Create a job ad) process. (In SAP an ad can be created in Graduate by checking a Graduate box.) There is no charge for dual-listing an ad in Main and Graduate. Dual-listing an ad means there is one JOB ID and two LISTING IDs. e.g. an ad can be dual-listed in MAIN/EXEC as Sydney/Accounting/Accountant (in Main) and Sydney/Accounting/Financial Controller (in Exec)",
"847b5db0-46f9-4670-9002-15fe85574ad8","FRACEL","A framework – part of CLASS Phase 1 Project - See Past IT projects jive page","FRAmework Config Engine Lightweight"
"87e88a5d-b22c-4801-af13-5322b296235c","SAM","Senior Account Manager (Field Sales) used to be called an IC (Internet Consultant).","Senior Account Manager "
"88b42248-52d8-481a-9d55-423c13887471","OWASP","The Open Web Application Security Project, an online community, produces freely-available articles, methodologies, documentation, tools, and technologies in the field of web application security.","Open Web Application Security Project"
"8d6c9aec-2f97-4288-8980-3671afcf6cc4","CLAPA","Correcting Links to Add-on Products for jobs ads project. Deployed under JSP R2 project in Jan 2011","Correcting Links to Add-on Products "
"90c66193-b3cf-431a-a2b1-540b7104c24a","IC","A SEEK sales representative. Some are state based and they deal predominantly with large volume customers","Internet Consultant"
"9768c2da-a7c8-4bdc-905d-4e3c0fc6d999","ATS","An Applicant Tracking System (or ATS) is an external system used by Advertisers to manage Job Applications. See also Applicant Tracking System (ATS)","Applicant Tracking System"
"9aec641e-b7af-4193-a247-52b0d6f133f2","EI","Employment Index, see SEI (SEEK Employment Index) ","Employment Index"
"9b6a7418-1f4b-4f74-87e2-ca4ab860c33b","SRP","The page that users land on after clicking the search button on seek.com.au","Search Results Page"
"9f3c1d6e-eb7e-49a3-9a6c-c40a4624768e","ICWEB","This is the web-based interface for our SAP CRM, used by CS and Sales for Account maintenance,","Interaction Centre Web"
"a27f6673-1ef0-4a6a-b64c-eed96beee8ee","Jabba","The project that removed the IT site from the SEEK website.",
"a462d273-03c7-48e0-bb05-3f561a1aaf6d","CPS","Customer Success Team & Client Product Specialist (NZ). These teams which were first created in work closely with our Hirers to give them support through education about our Products, particularly anything new. This helps them get the best out of SEEK.","Customer Success Team & Client Product Specialist"
"a6dbec73-12cd-41a6-a270-98565d1e05f4","KUPS","When a jobseeker is searching on the SEEK website, and they enter a keyword, e.g. Accountant Sydney, because Sydney is a location, it will return all jobs which contain the word Sydney as well as jobs with the location of Sydney. In addition, because Accountant is a classification, it will return all jobs with a classification of Accountant.","Keyword Upsell"
"a6f375f2-ff94-4eba-904e-46c7c8727343","Premium Listings","See premium Ads/PA",
"ac314972-ef3a-4bde-98a6-ca60aea6276f","Granular Location","Granular location involves adding the suburb & postcode for every ad in CAJA (Creating a Job Ad on the website), so that candidates can search for job ads in a specific location. This is an Hirer stream & Search stream project - see Finding Granny (Granular Location).",
"ae648071-645b-4adc-9672-09c7a88e1418","ITA","Also called Send Job. The ITA (Invite to Apply) project provided Advertisers with the ability to send an email to a Jobseeker with details for their Job ad. The button within the Jobseeker Profile product is called 'Send Job'. This functionality was implemented as part of the Invite To Apply project - Release 1 (end of August 2013). Advertiser are allowed to invite a Jobseeker once per Job ad. They are allowed up to 20 invites per Job ad. If a Jobseekers profile has already been purchased or they have already applied for this job ad, then the Jobseeker is not able to be invited or purchased.","Invite to Apply"
"b7738304-4c06-4263-8c4a-1bb8751decc7","Fast","A powerful indexing engine which we use for job searching and indexing of resumes. For more details see the @SEARCH project page",
"bf2dc48d-77e5-4fcd-a3cf-a0ae08aa2d8e","SBS","Search by Salary project","Search by Salary"
"c2958f2a-4544-4999-9d19-6c87bb381038","EMIS","Executive matches in SEEK. Displays links to relevant Executive Functions from Main search results & directs more traffic to SEEK Exec","Executive matches in SEEK."
"c76d358e-cf74-462f-8283-badbc1a86b1c","Rasci","Responsibility Assignment matrix which clarifies roles and responsibilities for a particular project or process.",
"c7a5c421-0bbf-4a7b-9be7-7fc78f7f16fc","Single-Page Visit","An Omniture site metrics term that shows you the pages of your web site that visitors enter and exit without taking steps to view any other pages on your web site. The data listed in this report identifies the number of your site's Single-page Visits and where your visitors enter and exit without viewing additional content.",
"c871b90d-4263-4deb-b057-cbbe44487088","RELOADS","An Omniture site metrics term. Counted when the same pageName is loaded twice.Some examples of reloads are defined below: By clicking Refresh, the original page loads into the browser. Reloads that are automatically refreshed by the web site. By leaving the site completely, accessing another site, and then clicking the Back Button so that the original page loads into the browser NOTE: If you have a page displayed in the browser for over 30 minutes, and then you click Refresh, SiteCatalyst does not register a reload because the visit  has been terminated and a new visit has begun.",
"d04c0279-1442-4502-b376-0ed9a22f1bc0","FAJA","A 2012 project to update our Search process.","Find A Job Ad"
"df00f382-0594-46ce-8c85-123b3f93efda","Multi-Listed Ads","Creating an ad once, but having it appear in more than one area e.g. Main/Exec or Main/Grad. See Dual-list and MAJA (Mirror a job ad).",
"df2c6ba1-dbcd-4064-92a3-0406565ccb36","PTS","   This differs from our standard Talent Search product as it provides hirers with more flexible ways to search for candidates. While standard Talent Search allows the hirer to search Profiles that match a live job ad on their account,    Premium Talent Search does this and more, allowing the hirer to openly search our entire database of over five million Profiles using refinements like location, title, company name or skills. It also includes the Approachability Signal which    helps hirers to easily gauge if a candidate may be actively looking and therefore more receptive to new opportunities. This is a paid upgrade to the standard Talent Search (which allows Hirers to search all candidates for a particular job ad). This allows Hirers to search for candidates that matches a job ad criteria, or to initiate an unrestricted search using their own search terms.","Premium Talent Search"
"e1fda4c6-4fc7-49df-8ece-b062c8b7536a","ASP.NET MVC","A more modern replacement to WebForms, providing a lighter weight approach to web development.",
"e437de37-76cc-43e9-b4f8-80343b85510d","LO","This allows jobseekers to apply directly for a job on the Advertisers website linking directly to the Advertisers application tracking system. Statistics of LinkOut starts are stored but no record of whether applications are completed can be logged.","LinkOut"
"e486c3ee-ace7-4853-85cd-7f67c8b36094","Application Queue Service","A windows service that processes items in the queue application table. The QueueApplication table contains references to each new job application that requires processing through @ShortCut or Native job application process.",
"e9109b04-1c7d-4db1-97d8-227b48f6b242","JobMail VISITS","An Omniture site metrics term. A visit to the site which has originated from a click on a link in the JobMail email.",
"ea7df4b9-280c-499d-aaa4-2cc8dbc5eb7a","UDDI","Is a directory for storing information about web services, is a directory of web service interfaces described by WSDL, communicates via SOAP and is built into the Microsoft .NET platform","Universal Description, Discovery and Integration"
"eb793c4b-18ea-4c6e-a308-7c68349ade14","Eyeball Minutes","A Nielsen/NetRatings market intelligence term. The total amount of time, reported in thousands of seconds, of all UBs spent on site in the reporting period (excluding time spent on final page of session, which cannot be measured). This is calculated by multiplying Page Impressions (PI) by Average Page Duration (APD).  The time spent on the final page of every visit is not capturable by Nielsen, refer to Hitwise Average Visit Time reports.",
"f06eb3ff-bf8e-4f25-a5f6-23592e73b181","SDLC","The old SEEK SDLC can be found here: http://teams/IT/Shared%20Documents/IT%20Processes/SDLC. In 2012 this was superseded by the Agile software development life cycle.","Software Development Lifecycle"
"f08ee36c-d259-4559-8b14-8cd0c6dcada4","SMART","SEEK Manager Replacement Tool – SMART pages were created to replace Seek Manager functionality that SAP couldn't support. e.g. If we need to modify a job ad we use SMART pages as SAP doesn’t store all information about a job ad.","SEEK Manager Replacement Tool"
"f3dbbeb5-3e22-4d72-b307-140f231f43c0","OOP/ OO","A form of programming that focuses on the use of objects containing data and the actions that can be performed on the data","Object oriented programming"
"fa59ab16-f2eb-45be-b29f-a460ebc21dee","Time Spent On Page","(also Average page duration) (An Omniture site metrics term. The Nielsen/NetRatings terms is Average page duration.) The amount of time (in minutes) that a visitor spends on a particular page on average.  It should be noted that the time spent on the final page of every visit is not capturable by Omniture To understand true time, refer Hitwise Average Visit Time reports.",
"03ed938b-6ac1-4ec7-8ab8-454676f24925","NPM","A package manager for the JavaScript programming language. It is the default package manager for the JavaScript runtime environment Node.js","Node Package Manager"
"0528eab2-8432-4c81-bd7a-bfffb12f9b87","Referrers","An Omniture site metrics term. A domain or URL used outside of your defined domain to access your site. The Referring Domains Report and the Referrers Report break referrer data into domains and URLs so that you can view the instances that visitors access your site from a particular domain or URL. For example, if a visitor clicks a link from Site A and arrives at your site, Site A is the referrer if it is not defined as part of your domain.",
"08747922-4569-4564-9d20-64d3f6943fed","SCM","Software Configuration Management is a team within IT. The Primary role of SCM is to facilitate the speedy movement of completed packages of software to Production in a consistent and reliable manner. See @SCM - Software Configuration Management.","Software Configuration Management"
"095f0cb2-8c04-4fc4-9566-1fbe56b49691","JAJA","Job Ad preview on Job Apply page. See - http://wiki/mediawiki/index.php/JAJA_User_stories","Job Ad preview on Job Apply"
"0db25832-633b-45d4-9675-8c30cbe58dfe","Average Page Duration (also Time spent on page)","A Nielsen/NetRatings site metrics term. The Omniture term is Time spent on page.The average time all pages (except for the final page in a session) were viewed on the browser screen for a selected period. This metric is calculated by dividing the total duration of Page Impressions that are less than 30 minutes by the number of Page Impressions. Note: If a page impression lasts 30 minutes or greater it is assumed that the page is no longer being viewed. This is removed from the total duration as it may distort the data.  The time spent on the final page of every visit is not capturable by Nielsen. True time is calculated by the Hitwise Average Visit Time reports.",
"11","AMI","A special type of virtual appliance that is used to create a virtual machine within the Amazon Elastic Compute Cloud (EC2). It serves as the basic unit of deployment for services delivered using EC2.","Amazon Machine Image"
"11a830e5-e77d-45e6-9b96-88bd5e91ab23","CAF","Used by the advertiser in ScreenCAF CAF ","Custom Application Form"
"140baff7-7da2-4be6-a375-4e25814d1fd8","RAMBO","Project Rambo (Relationship Acquisition Method Best Outcome) addressed the problem of Hirers being unaware of the JSP product and having no authorization/capability to access JSP matches for their job ads (specifically Third Party Partners who upload ads in bulk and don't use the SEEK website). It allows all hirers to personally establish a hirer account with SEEK. This project ran during April/May 2014.","Relationship Acquisition Method Best Outcome"
"151fc5f9-a20b-4738-a789-786467b1fee3","Job","A job is the detail of the job ad. A job can have one or more listings. The details are stored at the job level and the classifications are stored at the listings level",
"17af2add-2051-4290-9a63-38f735dafcc8","Zone","A SEEK website can be divided into separate partitions called Zones. E.g. The Australian SEEK website used to be divided into SEEK, SEEK Executive and SEEK IT zones. Similarly, the New Zealand SEEK website was once divided into SEEK and SEEK IT zones.",
"1baecba2-45f9-49c0-ad21-689328364f2f","RSS","SEEK provides an RSS feed which alerts you through the day as new jobs are listed on the web site.  http://rss.seek.com.au/rss.aspx?Keywordsa&RMmain&RMit&RMOmodel-main&RUSSEEKMAIN_USR&RID192752  RSS was retired in January 2012 due to its low usage rate by jobseekers.","Really Simple Syndication"
"1fd0b9e2-00cb-4b9e-a2da-276f269fa87c","CSI","Customer Satisfaction Index - See MARKETING jive page","Customer Satisfaction Index"
"29357c79-d1d6-41ed-ac82-485dace5ad49","DTC","The Distributed Transaction Coordinator (DTC, or MSDTC) is a service within Windows that allows for transactions that span multiple resources (eg a database and a message queue). If a given transaction requires for example a new record in a database and a new message in a message queue, and one of these fails, DTC will be responsible for rolling the entire transaction back on all resources.","Distributed Transaction Coordinator"
"29910174-f39a-4a6d-8100-8fb9e00301b8","LMIS","Learning Matches in Search. See Learning Matches in Search (LMIS) Jive Page","Learning Matches in Search"
"2cba340c-9c4e-4d6c-8375-0cf4e5014f59","BIL","BIL was a project in involving the upgrade to BizTalk 2010.",
"2d545358-a6ff-4266-805d-b987d23b9303","Job Application Details","Includes SEEK’s internal application client’s job reference, application submitted date, SEEK’s jobseeker ID (if it exists).",
"2e145bda-f2d5-4c65-ae03-66438aa4cf61","Resume Search","Resume Search now called Jobseeker Profiles -  JSP which allowed Advertisers to search through Jobseeker’s resumes for potential job candidates. The JSP project was completed in April 2011.",
"335f56a9-2cd5-4c91-93ec-a267f7c3296f","SITA","Ensuring Candidates sign in when they apply for a job.","Sign In To Apply"
"362770b4-1974-4905-b0a6-1916df930c63","External Referring Urls","A Nielsen/NetRatings site metrics term. The Omniture term is Referring URL. The URL (or specific page)  your visitors came from before they were on your site. Requires user to have clicked on a link to your site from the referring site.",
"37c6f940-84f5-47f6-9a05-84d54d29925d","BOOST","(SAP Implementation Project 2007). For more information see the BOOST file repository","Back Office Operations and Systems Transformation"
"423277c8-6037-4e3e-a1ac-cb21e8622be9","Ultra SAT","Those working in the high turnover, low skills, localised markets e.g. wait staff, bar staff, labourers, and retail assistants (SAT/SAT on the other hand, tends to apply to Office Workers).",
"43f5df02-fe57-4e3a-ad21-8ea1997e1882","JAR","The JAR (Job Apply Rework) project aims to update the Job Apply process. It is part of the Engineering Stream","Job Apply Rework"
"441d6f52-d59f-438f-9c0f-3288b96cb9d2","JSP","A Jobseeker profile is made up of a resume provided by the jobseeker and a summary of their experience, skills and ideal job information, entered into our system by the Jobseeker. Jobseeker Profiles - JSP   was also the name of the Jobseeker profile project which replaced the old Resume Search application. It allows storage of jobseeker resumes and profiles.  It allows advertisers to head-hunt jobseekers using the details they have stored. Also Jobseeker Promise","Jobseeker profile"
"44370a5a-0858-41c0-a141-af8852831d8b","AB","Andrew Bassat, CEO of SEEK","Andrew Bassat"
"4577fe7e-51c4-4e2c-a7f0-948baf7195a1","UCC","A project that merged our advertiser centres (SEEK, Campus, Exec) into one advertiser centre.","Unified Client Centre"
"5019f6cf-9419-44c9-83e8-6e77b38256a4","Search From","An Omniture site metrics term defined as the date range/s selected in job searches",
"539bb838-5fe1-4c40-9781-fe90f86782a5","Search Specialisaion","An Omniture site metrics term defined as the specialisation/s selected in job searches.",
"551bcdfb-7481-496e-8f68-f001dc423856","Classic Ad","A standard ad i.e. non-Standout ad/non-Premium ad",
"553c001a-29fc-47cd-a5d9-37b942d6843d","RRT","The Rapid Response Team was replaced by the Application Support team in IT Ops & Apps","Rapid Response Team"
"55429e44-9636-4420-8dc9-801bde53a96c","ENADS","Enhanced job Ads, also StandOut Ads","Enhanced job Ads"
"55c2b193-ed94-4bed-8fca-d684b08daa75","BA","See the Employer Branding / Display Advertising Collateral Jive page. Also Business Analyst","Banner Ads"
"585be3fe-1525-46f2-ae36-1b6cb8e23ec1","Search Classification","An Omniture site metrics term defined as the classification/s selected in job searches",
"5b928fca-b39b-4fab-af3e-fa0e6649f8ec","PIR","Post Incident Review","Post Incident Review"
"6154c4ec-b337-440f-998c-388ec54d1d8d","BI","See Fastlane Plus Project (Bulk Imports) Jive page Also Business Intelligence","Bulk Imports"
"642f1cc9-55b4-4809-a411-4ee5b475f273","RPO","RPO pricing has been developed for recruiter clients (Hays etc) who offer onsite recruitment to their clients. An example of this would be a recruiter who has their staff sitting onsite at a company like GE, Commonwealth Bank, Telstra etc. and this team only recruit for this one client and normally on a long term contract basis. Technically this client (Telstra etc) is not eligible for SEEKs recruiter rates. RPO is a process/pricing group set up so these clients can be billed. The main recruiter is still responsible for these contracts, pricing and agreements. See  RPO Agreement","Recruitment Process Outsourcing"
"65a437f6-8b22-48e5-849b-9e82f6beca8f","Billing","Generically used to describe Customer interactions relating to payments  E.g. Casual customers vs Subscription customers vs Pack customers. See Finance Operations for more info.",
"66404e15-19ad-4f38-b699-5541d09861eb","F#","Microsoft's functional first programming language that originally started off as a research piece then made inroads into the scientific and financial programming communities. It has now reached a reasonable level of interest and curiosity within the general programming community. It's typically referenced along with Scala as a modern multi- paradigm language, allowing developers to take the best from functional and object oriented programming. Real developers do functional.",
"6e8f3814-e126-4093-ad2f-ac6a7763a8cd","Bigtrak","Bigtrak is the name for the automation tool used by the IT QA department at SEEK in 2012",
"6edb3193-0642-4b1f-8d1f-d61438440664","JOBSEEKER","Jobseekers are people that look for jobs on the SEEK website, they may or may not be registered.  They are referred to as candidates on the Advertiser website. Note: the correct spelling is Jobseeker. Now referred to as Candidates.",
"747d66c9-d8a6-460e-b246-a5f16081e745","Esm Advertiser","Early Stage Market Advertiser. An advertiser that predominantly uses other forms of advertising rather than online.  These areas are Education, Healthcare & Government","Early Stage Market Advertiser."
"7a4ed6da-a48b-47fa-b405-48be3973e666","Jobmail","Emails sent out to jobseekers that contains jobs that match their job search profiles.  The Jobmail process starts executing at approx 12:05am every day and has a completion SLA of 9am.",
"7cae72ec-0dbc-4165-a213-86199c5900e6","Alliances","A site setup for companies that pay for the privilege of having their own customised top bar.  These are controlled by cookies and are arranged through the UI Dev Team.",
"7ddeacbe-0713-44f6-990e-d35e77d7d3bd","EFS","A simple, scalable, elastic file system for Linux-based workloads for use with AWS Cloud services and on-premises resources. It is built to scale on demand to petabytes without disrupting applications, growing and shrinking automatically as you add and remove files, so your applications have the storage they need – when they need it.","Elastic File System"
"80d13aaa-fee4-4902-bfb6-dae29b956b39","SKU","SKU is an internal front-end development toolkit, powered by Webpack, Babel, CSS Modules, Less, ESLint, Prettier, Jest and Storybook. Quickly get up and running with a zero-config development environment, or optionally add minimal config when needed.  Github repo here: https://github.com/seek-oss/sku",
"80f6e992-4b79-46bf-8be0-6c6d50c0b1db","DOLLY","Find People Like This feature within Premium Talent Search - for more information, see May 2018 Talent Search Hirer Usability Testing - Dolly Updates Validation Jive Page",
"8703c246-b24c-438f-8083-a5f7e0d8ddc0","Mobile","The Mobile Apps stream is an Online Delivery stream to enable jobseekers to access all functionality from the SEEK website on their mobile device",
"899e4b30-5c48-48c4-8e63-71ce3f5d7e68","CDN","A system of distributed servers that deliver web content to users","Content Delivery Network"
"8d104673-6bac-4051-83c6-d119e45992a9","SOAP","A communication protocol; is for communication between applications; is a format for sending messages; is designed to communicate via Internet; is platform independent; is language independent; is based on XML, is simple and extensible; allows you to get around firewalls and will be developed as a W3C standard. We use this with our Fastlane Plus","Simple Object Access Protocol;"
"8f219ed2-d272-481e-b435-4d3cf2c6af4d","SSO","A property of access control of multiple related, yet independent, software systems. With this property, a user logs in with a single ID and password to gain access to a connected system or accomplished using the Lightweight Directory Access Protocol (LDAP) and stored LDAP databases on (directory) servers","Single Sign On"
"93aec08d-9d47-46fc-a705-27e0ed6de997","Seek Facelift","On 13 June the SEEK website was updated to make the site more modern and visually appealing. SEEK Facelift changed the tools on the search results to make them more prominent and changed icons and labels inline with the mobile app and website.",
"94fd57ea-2c92-4820-bd3c-918924c7a482","CAJA","Often used for anything to do with the job ad creation process. For more information, see Create a casual job ad Jive page. See also Express CAJA definition.","Create a Job Ad"
"9699b578-56dc-40ea-b431-d65a47ddaeff","MoM"," Month on Month (a finance term) i.e. May-13 vs. April-13","Month on Month"
"96e88c6d-a1ef-40d5-a8a2-0fa2f9b13581","PASS","Premium Ad Self Service (a project that replaced the Premium Listings spreadsheet), which allows Advertisers to book Premium Ads online. See Purchase a premium ad online - PASS","Premium Ad Self Service"
"9e195679-989b-4d82-9bec-cfab3b0a244f","SSL","Secure Sockets Layer is technology that provides secure encrypted communication over the Internet. See the http://www.verisign.com/ssl/ssl-information-center/how-ssl-security-works/index.html","Secure Sockets Layer"
"a40c4c0f-d385-4325-998f-f9d2111d22a2","Search Area","An Omniture site metrics term defined as the area/s selected in job searches",
"a5c973b2-0d57-47c2-89fe-b5244ab7cb7b","Unique Browsers","An Omniture site metrics term. The Nielsen/NetRatings term is Unique Browsers. A visitor is a web browser (i.e. a computer's interface to the web) that accessed your web site.Unique visitors represent the number of unduplicated (counted only once) visitors to your website over the course of a specified time period. A unique visitor is determined with cookies. Unique Visitors are unique to the reporting period and cannot be summed across reporting periods or sites.Unique Visitors do not equal  'a person' as multiple people can access via the one PC/browser or  a person may use multiple browsers ( from home and work) or may delete cookies.",
"a7bf2667-416f-49f0-a356-e2b388ca129d","JVM","Despite the name, this virtual machine interprets byte code compiled from more than just Java (Scala and Clojure to name a couple) and then runs it as native code","Java Virtual Machine"
"aa61c677-31ee-4466-9adc-73df55fe69b5","SEEK","SEEK the company. Always in uppercase. If using it as a noun (for example the company), use SEEK.  If you are using it as a verb (for example What are you seeking?), then it is in lower case. The logo uses the word seek in lower case. For more information about SEEK branding refer to the SEEK Brand Guidelines",
"abd54d98-fde1-466e-b571-8531f92904de","JAD","Joint Application Design is an architecture forum for rapid solution development","Joint Application Design"
"ac0586f9-5c49-4c85-90e4-781d59f321b3","VB","Another Microsoft language created to appease the lowest common denominator. You are free to mock and look down upon those who prefer this.","Visual Basic"
"af983fdd-cd07-45ac-b537-dafe476fdfb1","Agents","Companies that work on behalf of multiple clients; they are media buyers. They login with their agent id which shows the list of clients they represent and this enables them to login as that client and create a job ad. They can also use Fastlane or Fastlane Plus to upload multiple job ads.",
"b31e8b8f-7ea2-4a9f-8f16-43544c313a58","SQUID","SQUID - Screen Questionnaires Indirect is an Hirer stream project running in that is updating the Screen Questionnaire component that Advertisers can add to their job ads, to screen a potential candidate e.g. Do you have the right to work in Australia?   ","Screen Questionnaires Indirect"
"b33b96c0-59a1-49e9-8ea9-7157c4c226fd","AngularJS","The AngularJS website describes it as what HTML would have been, had it been designed for building web-apps. It is an open-source JavaScript framework. According to Wikipedia, its goal is to augment browser-based applications with MVC capability and reduce the amount of JavaScript needed to make web applications functional.",
"b3477a27-8d9b-4d77-ba70-4bd13698ede3","BOB","A Developer project team from 2010",
"b6788556-efe4-4395-baac-c53ee66456df","Co-Brands","Now called co-brand alliances.  Examples of these would be Ninemsn, Xtramsn and Yahoo.",
"b75cfb06-7ca0-4cac-a4fb-5aea660bc364","BOLT","The BOLT project from 2012 had the aim to create better Jobseeker profile data for advertisers. It was the second Agile pilot project. BOLT R4 was deployed Feb 2012 and included adding additional fields (P1 data fields, such as current role and company) in the application form.",
"b79e39e7-c6c6-4aac-9d00-3cdc4e6519a7","Biztalk","Biztalk sits between Online and SAP and transfers messages between them, as Online and SAP cannot directly talk to each other. For more information see Troubleshooting BizTalk",
"ba854dc4-0797-48cc-829f-6806362bba40","Data Miner","This is a service that keeps the content of FAST in sync with the main SeekWeb database (see SeekWeb).  It adds and updates changed and new content and deletes expired ads from the FAST index. Note: The search engine FAST has been replaced with Cloudview",
"bee93181-64c3-48dc-a08c-18ee4e697044","Fastlane Plus","Advertisers can write their own webservices client that automatically pushes multiple jobs to our website and synchronises it with our database.",
"bf894d93-da54-421a-835c-08c817d656af","UI","Also the Web Production Team team - the User Interface team that controls the content on the SEEK website","User Interface"
"bfd1cf33-6e32-4c5e-b1be-29aa26cd8293","JobMail PROFILES","An Omniture site metrics term. The number of JobMail profiles created (first or addditional) within a specified reporting timeframe.",
"c22bb55c-35d1-40a8-954d-ce5837d7b3f3","Average time on site (also Average Session Duration)","An Omniture site metrics term. The Nielsen/NetRatings term is Average Session Duration. This shows the average length of a User Visit (up to, but not including the final page viewed). Also known as visit length. The time spent on the final page of every visit is not capturable by Omniture. True time is calculated by the Hitwise Average Visit Time reports.",
"c6412d85-1991-4d66-af3d-55e75e704d16","CMB","Change Management Board at SEEK.The CMB consists of a number of PD&S & IT Ops & Apps managers who approve all changes to the SEEK website, to infrastructure.","Change Management Board"
"c72ce15a-c0cd-4d03-acf0-43b235d2e795","JAM","The JAM (reworking Job ad management) project was the initiative to replace the VersionNet legacy code which has little automated test coverate, is difficult to change and causes high severity incidents.","Job ad management"
"c744b02d-3f2c-4866-93a6-71d1d2461b98","SAT/SAT","SAT/SAT is a segment of our market which includes lower skilled roles with a high number of people applying for them (e.g. cleaners, waiter/waitresses, office workers). See What is Max/Max & Sat/Sat?",
"c9fcb53e-76fd-4914-9398-82af5fdd1a06","IM","Often used to refer to Premium Ads but actually includes Jobmail slots (no longer used) and Banner Ads/Feature tiles - see Inventory Management (IM) Jive page","Inventory Management"
"d468a80c-49e2-4138-ab60-460d04c56a1c","IL","This is the name that is given to the byte code run by the CLR (a separate programming language focused virtual machine - see CLR). This where code from a high level language, such as C# or Java, is compiled into byte code that is then run by the virtual machine. The majority of the code we develop is written in C# and run on the CLR, but we have services such as CloudView that are written in Java and run on the JVM.","Intermediate Layer"
"d6a3c788-cb9d-4ea8-87a2-00d09e730358","Online","Usually refers to the SEEK website www.seek.com.au",
"d717f27e-0c66-4ed3-9f9f-7c8d2528d2c4","VM","Can refer to a fully virtualised machine, such as VMWare, where an entire OS can run inside another application. This is where we're heading with our servers. Alternatively it can refer to a separate programming language focused virtual machine such as the JVM or CLR. This where code from a high level language, such as C# or Java, is compiled into byte code that is then run by the virtual machine. The majority of the code we develop is written in C# and run on the CLR, but we have services such as CloudView that are written in Java and run on the JVM.","Virtual Machine"
"da1dd704-d811-454f-afb8-d63bedc6c36d","BOSS","Better online self service project which was aimed at improving the advertiser center.","Better Online Self Service"
"dd287ae3-a187-4a0b-b0ae-f77605415341","External Referring Domains","A Nielsen/NetRatings site metrics term. The Omniture term is Referring domain. The domain your visitors came from to access your site. Requires user to have clicked on a link to your site from the referring site.",
"dd5d1454-c48b-4f4e-96cc-050bd8010f0e","P1 data","Priority 1 job seeker data. This data can be used to autofill fields in a jobseeker's JSP profile and future products. It is called Priority 1 because Hirers have identified this data to be of premium importance to them. P1 data was identified during the BOLT project  and consists of Job title Time in Role Company name Is new to the workforce?",
"dd8fc3ba-a1ba-4fb2-a05a-913384d4fdfa","Pricing Engine","In SAP there is a pricing engine that works on product codes to determine price eg AUSKJOB is the product code for a job on the Australian website",
"e30b43fa-3a21-4ed6-b5a8-d30b99e31bea","HTTPS","When logging on to secure Web sites, the URL starts with HTTPS rather than HTTP. The 'S' indicates a secure connection. HTTP Over SSL. Protocol enabling the secured transmission of Web pages. A secure version of HTTP which encrypts data.","Secure Hyper Text Transport Protocol"
"e4d0e4e8-a35e-433c-bd8f-2e327459abcf","SCOM","Part of the SEEK family and is a marketplace for businesses and franchises for sale across Australia. See http://www.seekcommercial.com.au","SEEK Commercial"
"e7b75d2b-4882-4e24-b9c5-bde5e32d6263","EOI","Expression of Interest – Jobseeker – can express interest in a company, job type or job. An expression of interest is not considered to be an application even though an EOI in a job could meet the above criteria.","Expression of Interest"
"e88353ae-6483-4a6d-afb5-88ef0f7a0628","3PU","A company that uploads multiple jobs to our website, and manages applications on behalf of multiple clients. Charlotte Montague & Lee Whitaker manage our relationships with our Partners. See Partners for more information","Third party up-loader or Third Party Partner."
"ec03b41e-4bfd-49d5-874d-9b3b923b684b","ITO","thing",
"eff7007e-a947-49af-b216-ec5dc9c98072","Seek Executive","SEEK Executive was a separate area of the SEEK network of websites which was aimed at senior and professional employees seeking roles that paid over \$100K. SEEK Executive featured StandOut ads for free. SEEK Executive website was retired on 1st October 2011. For more information see The specified item was not found.",
"f8b18474-d616-43b6-bea8-5340c75ddc36","JYMHM","aka Project Bradbury from the Notifications stream, a jobs you may have missed section has been added to JobMail to solve the problem of JobMail candidates missing out on the most relevant jobs if they don't open their JobMail emails every day or visit SEEK. See Bradbury (Jobs you may have missed) Product showcase_05102016 for more information.","Jobs You May Have Missed"
"f8e5d6f6-1255-4a89-81af-b46918b0d94c","FOP","An enhancement to provide advertisers with the option to request login details via the website. See Update Advertiser account details/Forgot password - old advertiser centre","Forgot password"
"f9a8b1a7-d6ff-46a7-920b-68a4995173a2","Express CAJA","Express CAJA is a cut down mobile-only version of the Create a Job ad process on the SEEK Talent website. This product launched in Oct to SME Direct Hirers who are new to SEEK. ","Express Create a Job Add"
"f9d1cbe5-feed-4262-b7ab-40c13329fd56","Page Impressions","See also Page Views A Nielsen/NetRatings site metrics term. The Omniture term is Page Impressions. A page view occurs when a visitor accesses a page on your web site. A Page Impression is recorded each time a page instrumented with the Nielsen//NetRatings code is displayed in a user's browser. This will occur whether the page is served directly from the web server, from a proxy, or from the browser’s cache.",
"fc1a24e4-7ee5-43c4-bfbd-bc48458dcf53","AD Registrations","An Omniture site metrics term. The number of advertiser registrations in a given reporting timeframe.",
"fe83eabe-480a-4d3f-8df7-e39a68ef254d","Job Application Attachments","Additional files associated with a Job Application. The files can be uploaded directly by the Jobseeker or written/completed by the Jobseeker and uploaded by SEEK. Attachments include Cover Letter, Resume, Screen and Selection Criteria"`;
